services:
  db_test:
    image: postgis/postgis:16-3.5
    ports:
      - "5432:5432"
    env_file:
      - .env-test

  redis_test:
    image: redis
    command: --port 6379
    expose:
      - 6379
    ports:
      - "6379:6379"