"""add account_id in table payments

Revision ID: 9ed69b57a47c
Revises: e30334a72fe0
Create Date: 2025-06-19 16:57:40.400209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ed69b57a47c"
down_revision: Union[str, Sequence[str], None] = "e30334a72fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("account_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "payments",
        "scores",
        ["account_id"],
        ["account_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "account_id")
    # ### end Alembic commands ###
