"""add users in data base

Revision ID: e30334a72fe0
Revises: b5735f0ae44c
Create Date: 2025-06-17 17:17:46.035724

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm
import bcrypt

from src.users.models import User
from src.payments.models import Score, Payment

# revision identifiers, used by Alembic.
revision: str = "e30334a72fe0"
down_revision: Union[str, Sequence[str], None] = "b5735f0ae44c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_hash_password(password: str) -> bytes:
    salt = bcrypt.gensalt()
    pwd_bytes: bytes = password.encode()
    return bcrypt.hashpw(pwd_bytes, salt)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    password_for_user1: str = create_hash_password("1qaz!QAZ").decode()
    user1: User = User(
        full_name="Admin1",
        email="admin1@lib.ru",
        hashed_password=password_for_user1,
        is_superuser=True,
    )
    password_for_user2: str = create_hash_password("2wsx@WSX").decode()
    user2: User = User(
        full_name="Sergey Petrov",
        email="petrov@mail.ru",
        hashed_password=password_for_user2,
        is_superuser=False,
    )
    session.add_all([user1, user2])
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
