"""create tables scores&payments

Revision ID: b5735f0ae44c
Revises: c160a21a0522
Create Date: 2025-06-17 17:08:35.950628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5735f0ae44c"
down_revision: Union[str, Sequence[str], None] = "c160a21a0522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "date_creation",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint(
            "transaction_id", "user_id", name="idx_unique_transaction_user"
        ),
    )
    op.create_table(
        "scores",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column(
            "balance",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("account_number", sa.String(length=20), nullable=False),
        sa.Column(
            "date_creation",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint(
            "account_id", "user_id", name="idx_unique_account_user"
        ),
        sa.UniqueConstraint("account_number"),
    )
    op.create_index(
        "idx_account_number_hash",
        "scores",
        ["account_number"],
        unique=False,
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_account_number_hash", table_name="scores", postgresql_using="hash"
    )
    op.drop_table("scores")
    op.drop_table("payments")
    # ### end Alembic commands ###
